[
    "Simeulue",
    "Aceh Singkil",
    "Aceh Singkil",
    "Aceh Singkil",
    "Aceh Singkil",
    "Aceh Selatan",
    "Aceh Tenggara",
    "Aceh Timur",
    "Aceh Tengah",
    "Aceh Barat",
    "Aceh Besar",
    "Pidie",
    "Bireuen",
    "Aceh Utara",
    "Aceh Barat Daya",
    "Gayo Lues",
    "Aceh Tamiang",
    "Nagan Raya",
    "Aceh Jaya",
    "Bener Meriah",
    "Pidie Jaya",
    "Banda Aceh",
    "Sabang",
    "Langsa",
    "Lhokseumawe",
    "Subulussalam"
]